### PR TITLE
[tree_sitter_v] Detach shebang from comment

### PR DESCRIPTION
**Pull request by Lycs-D**

### CODE REVIEW

**Comment by JalonSolov** [comment]
Ah, as in treat it as it's own thing, instead of a regular comment.

**Comment by ttytm** [comment]
In Vs at it is treated as comment but for ts it works nicely as it's own thing I guess :+1:

**Comment by JalonSolov** [comment]
Yep, I like the idea.  It is, after all, a very specific/special type of comment.

**Review by spytheman — APPROVED** [review]
Excellent work. Thank you 🙇🏻‍♂️.

**Pull request merged**
