### PR TITLE
docs: fix for Neovim LSP/Mason

### PR DESCRIPTION
**Pull request by lcheylus**
- add URL for mason registry
- add URL for mason-lspconfig.nvim plugin (':LspInstall' command)
- add URL for mason.nvim plugin (':MasonInstall v_analyzer' command)

### CODE REVIEW

**Comment by ttytm** [comment]
Thanks for pointing that out. Last time checked, it was installable  with lspconfig. If it isn't anymore, a fix should be submitted upstream imho. The LspInstall command is more commonly used for language servers and MasonInstall works then inherently

**Comment by lcheylus** [comment]
**There is no `LspInstall` command** in lspconfig Neovim plugin, see docs => https://github.com/neovim/nvim-lspconfig/blob/master/doc/lspconfig.txt
The lspconfig Neovim plugin is only used for LSP servers configuration, Mason is used for installation. Personally, I always install my LSP servers (C, Go, Rust, Lua, Python) manually, not via Mason.

I don't know how you were able to run it ?!?!

**Comment by spytheman** [comment]
Can we keep both?

**Comment by lcheylus** [comment]
> Can we keep both?

No, reference to `:LspInstall` must be removed in README: this command does not exist in Neovim  `lspconfig` plugin.

**Comment by ttytm** [comment]
Yep it's true what you are saying for default lspconfig. I'm referring to [mason-lspconfig] (https://github.com/williamboman/mason-lspconfig.nvim)

**Comment by ttytm** [comment]
> Can we keep both?
> 
> note: personally I do not use neovim, so it may not make sense at all, in which case, tell me to shut up.

Weighing up the options and beeing over pedantic:
Keeping it both is no harm and would prevent such misconceptions. Its weighing Tho if users have missed to install mason-lspconfig and only use mason.nvim they are missing out on some features that's are intended to work together. So forcing them towards there luck might eventually be better for the users. If someone knows about it and is deliberately not using it MasonInstall still works for those who know what they are doing

**Comment by lcheylus** [comment]
Fix my PR:
- add URL for mason registry
- add URL for mason-lspconfig.nvim plugin (':LspInstall' command)
- add URL for mason.nvim plugin (':MasonInstall v_analyzer' command)

**Comment by ttytm** [comment]
I just see we already have both commands. In my memory it was just `LspInstall` without mentioning `nvim-lspconfig`. My comment regarding not to add `MasonInstall` makes less sense than.

Clarifying the current commands is fine 👍

**Comment by spytheman** [comment]
Is it good to merge as it is now?

**Comment by lcheylus** [comment]
> Is it good to merge as it is now?

Yes :)

**Review by ttytm — APPROVED** [review]

**Pull request merged**
