### PR TITLE
docs: provide quickly accessible instructions

### PR DESCRIPTION
**Pull request by ttytm**
Currently, it is easy to lose overview or to miss information in the instructions of the readme since providing instructions for different platforms and editors can easily become mixed up.

E.g., we have instructions for installation followed by building, then a setup section that mixes some general settings with VS Code related settings then coming to editor specific setups.

To solves this I set up some wiki pages.
With the updates to the readme an overview is provided that allows users to access instructions more targeted and directly (and in potentially in more detail). This should help users more easily get v-analyzer up and running.

Rendered preview on the fork: https://github.com/ttytm/v-analyzer/tree/docs/wiki?tab=readme-ov-file#usage

### CODE REVIEW

**Comment by spytheman** [comment]
The Wiki is a github feature, and is not part of the cloned repo.

Imho the README should have enough actual instructions in it, for building the project, not just links to a wiki.

**Comment by ttytm** [comment]
I think it depends on the project if it makes sense. Since an lsp is cross-platfrom and cross-editor it imho helps to keep an overview and get qicker to what is searched for. To share example of LS projects that I use daily:

- https://github.com/rust-lang/rust-analyzer
- https://github.com/golang/tools/tree/master/gopls
- https://github.com/LuaLS/lua-language-server

To extend the list those are some first finds doing a qiuck search:
- https://github.com/MaskRay/ccls
- https://github.com/haskell/haskell-language-server

**Comment by ttytm** [comment]
As an alternative I'd add another MD file to better structure the instructions and add a TOC / some links to the headings in the readme and markdown file.

**Comment by ttytm** [comment]
K I gonna look into something md based.  

The docs folder that only held assests is no there anymore since 😬 882fb1533f8de07c247cf2189bc439da818dd231

Maybe a `INSTALL.md` in the root, we can also add a `CONTRIBUTING.md` if we have enough instructions for it.

**Pull request closed without merging**
