### PR TITLE
refactor: decouple tree_sitter grammar

### PR DESCRIPTION
**Pull request by ttytm**
The PR detangles how we currently interact with tree_sitter.

While the latest state of the PR gives us one `tree_sitter_v` module for the api bindings and the grammar, those distinct features are still decoupled and self standing. This should make things more structured and straightforward to use and easier to test.

_Quicklinks if comparing the project trees in the github UI helps:_
- https://github.com/vlang/v-analyzer/tree/59d104a4f3a860c71bdd93f6c897a2139b0f369b
- https://github.com/ttytm/v-analyzer/tree/refactor/decouple

### CODE REVIEW

**Comment by spytheman** [comment]
Please rebase over latest `main`.

**Comment by spytheman** [comment]
Just `tree_sitter` is a bad module name imho, since it is easy to confuse it with the tree sitter project itself. Can we use something more distinctive?

**Comment by spytheman** [comment]
Even a code name like `vitter` or `graffiti` will be better imho.

**Comment by spytheman** [comment]
Or `tree_sitter_wrapper` ?

**Comment by ttytm** [comment]
It's a binding to `tree_sitter` to be able to use the project itself why I thought it fits well.

I'll use one of the suggestion or if I think of something I'll drop it in.

**Comment by ttytm** [comment]
So personally I would keep it. From the suggestions I like tree_sitter_wrapper best so far.

**Comment by ttytm** [comment]
Gonna rebase this evening. On run at the airport now.

**Comment by spytheman** [comment]
Have a nice trip.

**Comment by ttytm** [comment]
Thanks!

It wasn't clear from the comments reactions to me, the bindings name remained with the rebase. You have the veto on this.

**Comment by JalonSolov** [comment]
I know it's a common way to reduce typing, but do we really want to have `import tree_sitter as ts`?

First, `ts` makes me think `typescript` not `tree_sitter`.

Second, V likes to be more explicit.

I think it helps readability to keep the longer name, even if it makes the lines a bit longer.

**Comment by ttytm** [comment]
@spytheman what about `tree_sitter_api`?

**Comment by JalonSolov** [comment]
I'd be ok with `import tree_sitter_wrapper as wrapper`, I think.  At least it's a bit more obvious what's going on.

Not a fan of `import tree_sitter { NodeType, Tree }` to get around typing the module name, either, as you can't tell from the code where NodeType is defined unless you scan the `import` lines.  Otherwise, it looks like it's declared in the current module.  :-\

**Comment by ttytm** [comment]
> First, ts makes me think typescript not tree_sitter.

Yes but if anyone works in the project where is no typescript usage and but tree_sitter the brain should be able to make the connection. At least for my brain there's no issue with it. I tried to adapt and making it better but imo the last commit is a worsening. So we disagree here.

>  Otherwise, it looks like it's declared in the current module. :-\

So this is a general dislike against Vs feature for selective imports

**Comment by JalonSolov** [comment]
I disagree about selective imports because it makes the code _less_ understandable.  Less explicit.

All it is, is a way to "hide" where something came from, just to have shorter things to type.

**Comment by spytheman** [comment]
> @spytheman what about `tree_sitter_api`?
> 
> then `as api` @JalonSolov ?

I am fine with that, and any other name, as long as the folder is not named `tree_sitter`.

It may seem pedantic, and petty, and I am sorry, but I *really* do not want to have any possibility of confusion with the tree sitter project itself.

**Comment by spytheman** [comment]
Btw, TypeScript and thus `ts`, is used for the vscode extension, which is in `./editors/code`, although it is unlikely that it will cause confusion, since the name conflict is in another level.

**Comment by ttytm** [comment]
Brought it into a project structure that hopefully makes all of us happy. It hopefully fulfills everything in terms of decoupling, structuring and naming.

The binding and grammar now both can reside in `tree_sitter_v`. The binding is accessible under `tree_sitter_v.bindings`.

**Pull request merged**
