### PR TITLE
[CI] Add `.vsix` artifacts to release asset uploads

### LINKED ISSUE #15: .vsix is not regenerated with other assests
### Describe the bug

image

### Expected Behavior

.vsix is updated at the same time as other assets.

### Current Behavior

.vsix is NOT updated.

### Reproduction Steps

Merge PR.  Check .vsix update.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### Environment details (`v doctor` output)

N/A

### Editor name

N/A

### v-analyzer Version

Latest

### VS Code Extension Version

_No response_

### PR DESCRIPTION
**Pull request by Lycs-D**
Fixed #15

### CODE REVIEW

**Comment by JalonSolov** [comment]
I don't see the `.vsix` file in the artifacts on the link shown.  Everything there is a `.zip` file.

**Comment by ttytm** [comment]
Good work. Please resolve the conflicts with the latest release workflow changes. The workflow now also includes uploads for regular release versions.

**Comment by ttytm** [comment]
Gonna look into the PRs soon. Sorry, about the delay.

**Review by ttytm — APPROVED** [review]
Good job :muscle: Thank you!

**Pull request merged**
