### PR TITLE
treesitter: correctly recognize shebang

### PR DESCRIPTION
**Pull request by ttytm**
Regardless of how we  we proceed with treating the shebangs in https://github.com/vlang/v/pull/21029

Currently, a shebang is not correctly recognized by tree-sitter. It's not highlighted and can break the highlighting of identifiers that follow it.

This PR aims to fix this.

- Current
  Screenshot_20240315_084339

- Updated
  Screenshot_20240315_084314

### CODE REVIEW

**Comment by ttytm** [comment]
Working on the regression regarding reference types introduced in the last commit.

**Comment by spytheman** [comment]
> Working on the regression regarding reference types introduced in the recent upstream commit.

what do you mean?

**Comment by ttytm** [comment]
> what do you mean?

Tests are failing here because of a change in https://github.com/vlang/v/pull/21025. It's fixed in https://github.com/vlang/v/pull/21030. I'll see to work out a test case

**Comment by spytheman** [comment]
Hm, I thought it was a pure refactoring, and the main CI tests passed. A test case will be much appreciated indeed.

**Comment by ttytm** [comment]
Thought so too. It slipped through. But if it gives us extended test coverage, it had its blessings.

**Pull request merged**
