### PR TITLE
build: prefer automatic generation of treesitter parser from grammar

### PR DESCRIPTION
**Pull request by ttytm**
The PR deletes and ignores generated static files in the repository.

This would remove the overhead that we are currently encountering in terms of repository size growth, additional effort and error potential.

Running `tree-sitter generate` will generate the necessary `src/` directory and files(keeping the src dir should not be required). Generating the files can be automated by projects that use the parser, like nvim-treesitter. It's an approach that e.g. tree-sitter Swift is using.

*Refs.:*
- Swift: 
  - https://github.com/nvim-treesitter/nvim-treesitter/blob/f87882858438834d2fbb6379aa2be37de901751b/lua/nvim-treesitter/parsers.lua#L1938-L1942
  - https://github.com/alex-pinkus/tree-sitter-swift
  - https://github.com/alex-pinkus/tree-sitter-swift/blob/main/.gitignore
- MILR:
  - https://github.com/nvim-treesitter/nvim-treesitter/blob/f87882858438834d2fbb6379aa2be37de901751b/lua/nvim-treesitter/parsers.lua#L1240-L1244L
  - https://github.com/artagnon/tree-sitter-mlir
- SCFG (uses the promoted approach without a src directory in the repo / ignoring it) - tested locally that the parser is working:
  - https://github.com/nvim-treesitter/nvim-treesitter/blob/f87882858438834d2fbb6379aa2be37de901751b/lua/nvim-treesitter/parsers.lua#L1750-L1755
  - https://git.sr.ht/~rockorager/tree-sitter-scfg/tree

Required for: https://github.com/nvim-treesitter/nvim-treesitter/pull/6300

---
**TODO**
- [ ] Update CI and tests work with file generation

### CODE REVIEW

**Comment by ttytm** [comment]
Before continuing on this, I'd like to confirm that the change the PR is trying to achieve has a chance.

I'd put the work to keep things running and testable with much convenience as possible then.

**Comment by JalonSolov** [comment]
Seems to me that automating things this way will mean the tool will be kept more up-to-date with the compiler, which sounds like a good thing.

Just have to keep the grammar updated.

**Comment by ttytm** [comment]
K started working on it. There are several more advantages that already reveal themselves in the process. The coming week is quite full. So I think the week after I'll push an update and leave an overview.

**Comment by ttytm** [comment]
Not planned for now backlogging for a potentially future version

**Pull request closed without merging**
